"""empty message

Revision ID: 0a4554d15202
Revises: b41b91912720
Create Date: 2018-09-29 12:20:07.472460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a4554d15202'
down_revision = 'b41b91912720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='category')
    op.drop_column('category', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('url', mysql.VARCHAR(length=200), nullable=True))
    op.create_index('url', 'category', ['url'], unique=True)
    # ### end Alembic commands ###
