"""empty message

Revision ID: 578ce7752a30
Revises: 4dd22a3476ce
Create Date: 2018-11-04 15:33:12.068991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578ce7752a30'
down_revision = '4dd22a3476ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('prop1', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('prop2', sa.Integer(), nullable=False))
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_ibfk_1', 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'prop2')
    op.drop_column('product', 'prop1')
    # ### end Alembic commands ###
