"""empty message

Revision ID: b41b91912720
Revises: f1573ab6c4aa
Create Date: 2018-09-29 12:17:49.577573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41b91912720'
down_revision = 'f1573ab6c4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('url', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'category', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'url')
    # ### end Alembic commands ###
