"""empty message

Revision ID: f1573ab6c4aa
Revises: 24635647d924
Create Date: 2018-09-29 12:13:41.992412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1573ab6c4aa'
down_revision = '24635647d924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('url', table_name='category')
    op.drop_column('category', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('url', mysql.VARCHAR(length=200), nullable=True))
    op.create_index('url', 'category', ['url'], unique=True)
    # ### end Alembic commands ###
